### ISSUE TITLE
embedding out of index

### ISSUE THREAD

**Issue by LiJinfen** [facebookresearch/SpanBERT#24]
Traceback (most recent call last):
  File "D:/workspace/semal_propaganda/SpanBERT-master/code/run_squad.py", line 1138, in <module>
    main(args)
  File "D:/workspace/semal_propaganda/SpanBERT-master/code/run_squad.py", line 971, in main
    loss = model(input_ids, segment_ids, input_mask, start_positions, end_positions)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\semal_propaganda\SpanBERT-master\code\pytorch_pretrained_bert\modeling.py", line 1199, in forward
    sequence_output, _ = self.bert(input_ids, token_type_ids, attention_mask, output_all_encoded_layers=False)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\semal_propaganda\SpanBERT-master\code\pytorch_pretrained_bert\modeling.py", line 730, in forward
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\semal_propaganda\SpanBERT-master\code\pytorch_pretrained_bert\modeling.py", line 268, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\jli284\.conda\envs\pro\lib\site-packages\torch\nn\functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 29483 out of table with 28995 rows. at C:\w\1\s\tmp_conda_3.6_171155\conda\conda-bld\pytorch_1570813991702\work\aten\src\TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by LiJinfen** [comment]
it is because of the vocab.txt, where can I get it? Thanks!
