### ISSUE TITLE
How to continually pretrain SpanBERT starting from a model checkpoint?

### ISSUE THREAD

**Issue by phosseini** [facebookresearch/SpanBERT#84]
I'm trying to run the pretraining code not from scratch but from one of SpanBERT's pretrained checkpoints (I have no problem in running the pretraining code from scratch). This is how I'm trying to do it but I get an error.

There are two possible checkpoints that could be used as the starting point (assuming I want to use the large model):

1. [https://dl.fbaipublicfiles.com/fairseq/models/spanbert_large_with_head.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/spanbert_large_with_head.tar.gz) (`model.pt`)
2. [https://dl.fbaipublicfiles.com/fairseq/models/spanbert_hf.tar.gz](https://dl.fbaipublicfiles.com/fairseq/models/spanbert_hf.tar.gz) (`pytorch_model`, that is the huggingface model)

**_The first question:_** which one of these models should I use? Or it does not really matter?

_**Second**_, assuming we have already chosen the right pretrained model checkpoint, when running the `train.py` I currently pass the `--restore-file model_name` since I saw that is the parameter from which the script reads model checkpoint's name (correct me if I'm wrong).

Then when I run `train.py`, after successfully loading the examples and data, I get the following error when model is trying to load the checkpoint:
```
Traceback (most recent call last):
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/train.py", line 387, in <module>
    main(args)
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/train.py", line 77, in main
    if not load_checkpoint(args, trainer, epoch_itr):
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/train.py", line 342, in load_checkpoint
    eval(args.optimizer_overrides))
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/fairseq/trainer.py", line 122, in load_checkpoint
    utils.load_model_state(filename, self.get_model())
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/fairseq/utils.py", line 68, in load_model_state
    state = _upgrade_state_dict(state)
  File "/content/drive/MyDrive/colab/SpanBERT/pretraining/fairseq/utils.py", line 88, in _upgrade_state_dict
    'best_loss': state['best_loss'],
KeyError: 'best_loss'
```
Obviously loading the checkpoint fails. I wonder what is the problem? And, how can I run a continued pretraining (meaning not starting from scratch and starting from the pretrained weights)?

@mandarjoshi90 any insight would be helpful.

**Comment by wasiahmad** [comment]
+1
